=== gravitee-io/gravitee-policy-generate-http-signature/src/main/resources/schemas/schema-form.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "scheme": {
            "title": "Scheme",
            "description": "Signature Scheme.",
            "type": "string",
            "default": "AUTHORIZATION",
            "enum": ["AUTHORIZATION", "SIGNATURE", "CUSTOM_HEADER"],
            "x-schema-form": {
                "type": "select",
                "titleMap": {
                    "AUTHORIZATION": "\"Signature\" HTTP Authentication Scheme",
                    "SIGNATURE": "\"Signature\" HTTP Header",
                    "CUSTOM_HEADER": "\"Signature\" Custom name HTTP Header"
                }
            },
            "gioConfig": {
                "banner": {
                    "title": "Signature Scheme.",
                    "text": "<ul><li>AUTHORIZATION: \"Signature\" HTTP Authentication Scheme</li><li>SIGNATURE: \"Signature\" HTTP Header</li><li>CUSTOM_HEADER: \"Signature\" Custom name HTTP Header</li></ul>"
                }
            }
        },
        "targetSignatureHeader": {
            "title": "Custom Signature Header",
            "description": "Specify the HTTP header that will contain the generated HMAC signature",
            "type": "string",
            "default": "X-HMAC-Signature",
            "x-schema-form": {
                "hidden": [
                    {
                        "$eq": {
                            "scheme": "AUTHORIZATION"
                        }
                    }
                ]
            },
            "gioConfig": {
                "displayIf": {
                    "$eq": {
                        "value.scheme": ["CUSTOM_HEADER"]
                    }
                }
            }
        },
        "keyId": {
            "title": "Key ID",
            "description": "The key ID used to sign (support EL).",
            "type": "string",
            "gioConfig": {
                "el": true
            }
        },
        "secret": {
            "title": "Secret",
            "description": "The secret key used to sign (support EL).",
            "type": "string",
            "gioConfig": {
                "el": true
            }
        },
        "algorithm": {
            "title": "Algorithm",
            "description": "The HMAC digest algorithm.",
            "type": "string",
            "default": "HMAC_SHA256",
            "enum": ["HMAC_SHA1", "HMAC_SHA256", "HMAC_SHA384", "HMAC_SHA512"]
        },
        "headers": {
            "type": "array",
            "title": "Headers",
            "description": "List of headers to use for HTTP signature creation.",
            "items": {
                "type": "string",
                "title": "Header"
            }
        },
        "signHeaders": {
            "title": "Include headers in signature generation",
            "default": true,
            "description": "Base signing process on the request/response/message headers",
            "type": "boolean"
        },
        "signPayload": {
            "title": "Include payload in signature generation",
            "default": false,
            "description": "Base signing process on the request/response/message payload (Required for response flow)",
            "type": "boolean"
        },
        "prependHeadersToBody": {
            "title": "Prepend headers to body for signature generation",
            "default": false,
            "description": "The defined headers will be prepended to the body for signature generation. (Only applicable if the signPaylonad option is enabled)",
            "type": "boolean"
        },
        "headersDelimiter": {
            "title": "Delimiter",
            "description": "Specify a delimiter to separate each header and the body/message",
            "type": "string",
            "default": ".",
            "x-schema-form": {
                "hidden": [
                    {
                        "$eq": {
                            "value.prependHeadersToBody": false
                        }
                    }
                ]
            },
            "gioConfig": {
                "displayIf": {
                    "$eq": {
                        "prependHeadersToBody": true
                    }
                }
            }
        },
        "signMethod": {
            "title": "Include request method in signature generation",
            "default": true,
            "description": "Base signing process on the request method name (Highly recommended for request flow)",
            "type": "boolean"
        },
        "signUri": {
            "title": "Include request URI in signature generation",
            "default": true,
            "description": "Base signing process on the request URI name (Highly recommended for request flow)",
            "type": "boolean"
        },
        "created": {
            "title": "Include the created timestamp in the signature",
            "default": true,
            "description": "Add (created) header in the signature. (Highly recommended)",
            "type": "boolean"
        },
        "expires": {
            "title": "Include the expires timestamp in the signature",
            "default": true,
            "description": "Add (expires) header in the signature. (Highly recommended)",
            "type": "boolean"
        },
        "validityDuration": {
            "title": "Validity duration",
            "default": 3,
            "description": "Signature's maximum validation duration in seconds.",
            "type": "integer",
            "minimum": 1,
            "x-schema-form": {
                "hidden": [
                    {
                        "$eq": {
                            "expires": false
                        }
                    }
                ]
            },
            "gioConfig": {
                "banner": {
                    "title": "Validity duration",
                    "text": "Signature's maximum validation duration in seconds. (Used only if the expires header is included in the signature.)"
                }
            }
        }
    },
    "required": ["scheme", "secret", "keyId", "algorithm"]
}

=== gravitee-io/gravitee-policy-generate-http-signature/.docgen/examples/response_signature_with_headers.json
{
    "scheme": "CUSTOM_HEADER",
    "headersDelimiter": ":",
    "headers": ["kafka-topic", "kafka-partition"],
    "keyId": "my-key-id",
    "secret": "webhook-signing-secret",
    "targetSignatureHeader": "X-HMAC-Signature",
    "algorithm": "HMAC_SHA256",
    "signPayload": false,
    "prependHeadersToBody": true
}
